### ISSUE TITLE
Need Bibliography for Oxford Book on Privacy Law

### ISSUE THREAD

**Issue by kellerscholl** [HumanDynamics/FreeLaw#12]
Available at the Internet Institute. Can you let me know what the book was that was published at Oxford. It's putting the personalized in personal data.

**Comment by dazzaji** [comment]
This task was retracted by the requesting professor.

**Comment by dazzaji** [comment]
Here is the information about the Oxford Institute book that includes a chapter I submitted as part of a conference.  Can you help find a copy of the book in electronic form so I can take a look at what I submitted (unfortunately no copy survived due to changes in archive and network storage assets here).  Thanks.

--- 

http://www.oii.ox.ac.uk/events/?id=302

International Expert Meeting on "Issues in Online Personalisation" Oxford Internet
Institute, Oxford, 5 March 2004.

Daniel J. Greenwood, The "Person" in "Personalisation"

-------

Daniel J. Greenwood, The "Person" in "Personalisation", paper presented at the International Expert Meeting on Issues in Online Personalisation, Oxford Internet Institute, Oxford, 5 March 2004. Greenwood further states: “ My favorite dictionary from the states is the Merriam-Webster, where the following definition of "personalize" can be found: "to make personal or individual; specifically : to mark as the SURSHUW\􏰀RI􏰀D􏰀SDUWLFXODU􏰀SHUVRQ <personalised stationery>". The OED defines personalize thusly: " To render personal; to represent as personal, personify; to embody in a person, impersonate; to make (some impersonal object or thing) more obviously related to, or LGHQWLILDEOH􏰀DV􏰀EHORQJLQJ􏰀WR􏰄􏰀D􏰀SDUWLFXODU􏰀LQGLYLGXDO” .


----- Forwarded Message -----
From: Daniel Greenwood <dan@civics.com>
To: Miriam.lips@oii.ox.ac.uk; a.m.b.lips@uvt.nl; events@internet-institute.oxford.ac.uk 
Sent: Tuesday, January 6, 2004 1:24 AM
Subject: acceptance: international expert meeting at OII 

Dear Professor Lips,

Thank you very much for the invitation, and I apologize for my delay in response.  I (apparently like you) find myself in the position of Visiting Researcher this semester and the adjustment and travel has set me behind in my correspondence (not to mention the holidays). I have written, lectured and consulted extensively in the general topic area of personalization and am enthused to participate in your event.  

Perhaps we can chat about the event and the topic in greater depth? Feel free to e-mail me some good times for you to chat by phone and I will call you at that time (taking into account the time difference, if you please).  My time is now quite open until January 12 and I'd be pleased to talk with you at your convenience prior to that date.  For the time being, please use my temporary e-mail address: semivirtual@yahoo.com or my mobile number in Australia (61-405-291-236). 

Warmest regards,
- Daniel Greenwood

==============================================
|  Daniel J. Greenwood, Esq.
|  Lecturer, Massachusetts Institute of Technology
|  Director, E-Commerce Architecture Program 
|  MIT School of Architecture and Planning 
|  77 Massachusetts Avenue, Room 7-231 
|  Cambridge, MA 02139 
|    http://ecitizen.mit.edu 
|    or http://www.civics.com 
|    dang@mit.edu 
==============================================


----- Original Message ----- From: Miriam Lips 
To: dang@mit.edu 
Cc: events@internet-institute.oxford.ac.uk 
Sent: Tuesday, December 23, 2003 3:32 AM 
Subject: invitation international expert meeting at OII 

Dear professor Greenwood,


Friday 5 March 2004: Issues in Online Personalisation 

I am pleased to invite you to The Oxford Internet Institute, University of Oxford, for an event organised in collaboration with the Center for Law, Public Administration and Informatization of Tilburg University, The Netherlands. On 5 March, we are holding an international expert meeting on developments of, and conditions for, the personalisation in online commercial and public service delivery. It will be held at the OII, located at 1 St Giles in Oxford on Friday 5 March 2004 from 10.00 – 16.30 hours. 

New information and communication technologies (ICTs) enabled commercial and public services to be more tailored to the individual needs and desires of customers. The prospects for businesses and governments in personalising online service and information delivery are such advantages as the improvement of the quality of service delivery, enforcement of rights (e.g. copyright), reducing costs, improving customer relations, and channelling of information overload away from customers. Besides possible organisational gains, however, the phenomenon of personalisation raises a number of important issues which may be crucial to its success. Examples of issues that need to be dealt with are the collection and use of personal data, data sharing between organisations, privacy protection, access to online services, identification, authentication, network security, legal norms (e.g. equality before the law, legal security), and the streamlining of internal organisation processes. 

During the 5 March meeting we would like to further explore various ways and related conditions (e.g. organisational, technical, social, legal, economical, political) for the personalisation of online services. An interim research report on this topic jointly prepared by research staff of the OII and Tilburg University will be the basis for further discussion. This research report will include the description and analysis of various case studies of personalisation applications in different countries. It will be send to all participants about a week before the expert meeting. In addition, we invite each participant to prepare a short individual position paper on the topic in general and/or more specifically in reaction to the report.

We would greatly appreciate your contribution to this debate. Please let me know if you would be able to participate in this meeting. As the meeting will be subsidised by the Dutch National Research Programme ‘Network of Networks’, we would be able to cover your travel and subsistence costs. Please do not hesitate to contact me if you have any questions about the event or your participation. 

Looking forward to hearing from you, on behalf of the OII and Tilburg University,
Yours Sincerely,


Dr Miriam Lips
Visiting Research Fellow
Oxford Internet Institute
1 St Giles
Oxford
OX1 3 JS
United Kingdom

Tel.: +44-(0)1865-287222 (direct) or 287210 (reception)
Email: Miriam.lips@oii.ox.ac.uk and a.m.b.lips@uvt.nl
